FROM golang:1.14.0-alpine3.11 as builder

WORKDIR /app

RUN apk add --no-cache make curl git build-base

COPY . .

RUN make build

FROM alpine:3.11

LABEL maintainer="dortiz@devops.faith"

COPY --from=builder /app/krakend /usr/bin/krakend

VOLUME [ "/etc/krakend" ]

ENTRYPOINT [ "/usr/bin/krakend" ]
CMD [ "run", "-c", "/etc/krakend/krakend.json" ]

EXPOSE 8000 8090
