ARG GOLANG_VERSION
ARG ALPINE_VERSION
FROM golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION}

RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    apk add tar make gcc musl-dev binutils-gold

RUN cd / && wget http://musl.cc/aarch64-linux-musl-cross.tgz && \
    tar zxf aarch64-linux-musl-cross.tgz && rm -f aarch64-linux-musl-cross.tgz

ENV PATH="$PATH:/aarch64-linux-musl-cross/bin:/aarch64-linux-musl-cross/aarch64-linux-musl/bin"
