name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Set up Go
      uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
      with:
        go-version: "1.25"

    - name: Test
      run: make test
